### PR TITLE
Discord Logging

### PR DESCRIPTION
**Pull request by FBFezz**
I worked on this on the manueljlz gcphone and got it to work. Tested and it logs it like this (Havn't Tested Photos yet)

https://prnt.sc/urv8pd

### CODE REVIEW

**Comment by FBFezz** [comment]
And this is what photos would look like

https://prnt.sc/urvagx

**Comment by RockySouthpaw** [comment]
Will test before next release is made.

**Comment by FBFezz** [comment]
Ok

**Comment by RockySouthpaw** [comment]
Implemented in next release with a config option.

**Pull request closed without merging**
