### PR TITLE
Update server.lua

### PR DESCRIPTION
**Pull request by c0deina**
Fix for newESX error.

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
This server.lua isn’t even used for the 1.2 releases. There is no reason to edit it.

**Comment by c0deina** [comment]
imagen

Clearly is being used in latest release.

**Comment by RockySouthpaw** [comment]
It’s not suppose to be. Taso did the release incorrectly.

**Comment by c0deina** [comment]
Allright, that's why the error popped and I did the pull request.

Have a good one.

**Pull request closed without merging**
