### PR TITLE
Fix twitter replies not @'ing the original author

### PR DESCRIPTION
**Pull request by xElementzx**
Its not the prettiest way to do it but it definitely works, the only downside to this is the modal when using mouse control no longer has @authorName.. mybad for this not being posted earlier, apparently by default github creates PRs on my fork when I do it -_-

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
@TasoOneAsia

**Comment by TasoOneAsia** [comment]
Will review here in a bit

**Review by TasoOneAsia — APPROVED** [review]
LGTM from web testing. This is fine until if/when we refactor twitter to use Router rather than the convoluted component state system currently in use.

**Comment by RockySouthpaw** [comment]
I’m gonna test this in game later tonight and merge it if all is well

**Comment by RockySouthpaw** [comment]
tested it and it work properly. We need to do some style changes so @RockySouthpaw is more defined like on github/discord

**Comment by RockySouthpaw** [comment]
FiveM_GTAProcess_LBecwTVwpa

**Comment by TasoOneAsia** [comment]
Easy enough

**Pull request merged**
