### PR TITLE
WIP - Possible mouse fix

### PR DESCRIPTION
**Pull request by TasoOneAsia**
Needs testing because of this absolutely stupid mouse bug that makes me want to tear my hair off and eat a cat. Since there is no consistent repro who knows if this fixes anything. I know this shouldn't make any of a difference at all. But hey I was asked to do it so here it is.

### CODE REVIEW

**Comment by RockySouthpaw** [comment]
0/10 PR. No meme

**Comment by TasoOneAsia** [comment]
no because i am sad

**Review by RockySouthpaw — COMMENTED** [review]
Didn't work sadly.

**Comment by itschip** [comment]
I heard the notes app works great

**Comment by TasoOneAsia** [comment]
Will mess around with this more tomorrow.

**Comment by itschip** [comment]
I dont quite understand how removing a css class with no properties will help

**Comment by TasoOneAsia** [comment]
As did I, none of the CSS should be causing this issue from first look. But I was asked to try it 🤷

**Comment by TasoOneAsia** [comment]
Possibly related but unknown without further testing

https://github.com/vuejs/vue/issues/10366

**Comment by TasoOneAsia** [comment]
Without much of a consistent repro, I really don't know what can be causing this CONSIDERING I was told this only was occurring in the CEF environment and not within regular browsers. Makes me believe oh hey, this is an issue related specifically to certain CEF environments. Whomst knows.

**Comment by RockySouthpaw** [comment]
You can try it on web but chips tried it on web previously and it was unable to reproduce the issue

**Pull request closed without merging**
