### PR TITLE
Offline bank transfers

### PR DESCRIPTION
**Pull request by erik-sn**
I saw the [idea to transfer money by phone number in the ideas thread](https://github.com/Re-Ignited-Development/Re-Ignited-Phone/issues/4#issuecomment-674472290) and thought I'd try to implement it.

This is the first fivem/ESX PR I've made so I'm definitely open to any feedback suggestions. I wasn't sure how to PR changes against `server.lua` as there seems to be 3 different places, the `resources/gcphone` and then the two `server 1-#` folders. It seems `resources/gcphone/server/server.lua` may be out of date/not functional so I PR'd it against the two server files since the instructions say to copy from there. Same code is copied to both of them.

Another caveat, this also requires [new banking resource](https://github.com/jacobwi/new_banking) which I assume to be implied, but as I'm new I'm not sure.

This PR:

- Adds the ability to transfer money by phone number
- Adds the ability to transfer money while the target player is offline (using their phone number)
- Modifies the UI to prompt for phone number as well as ID
- Maintains all current abilities to transfer money by ID
- Fixes bug where keyboard inputs that were numbers were not accepted by the input fields (calling `.trim` on a number)

I have tested these changes locally on Server 1-2, I can also change to Server 1-1 and change my `es_extended` as well. A

### CODE REVIEW

**Comment by erik-sn** [comment]
@BTNGaming I got a 1.1 es server running and it seems due to the SQL difference in bank/accounts this PR's offline functionality would not work (phone number still does).

Would we want to support both? I assume it's probably easy enough to figure out which es_extended is running and I can run a different SQL statement in that case.

**Comment by BTNGaming** [comment]
We would want to support both because it is made for 1.1 and 1.2 technically.

**Comment by erik-niehaus** [comment]
Hi @BTNGaming I updated this PR to work with ESX 1.1. Sorry for the delay I had a bit of trouble getting my 1.1 to work locally, all good now.

I'd appreciate any testing you can do on this. Here is the test plan I went through on both ESX 1.1 and 1.2:

Target Player **offline** - Transfer by ID: Should FAIL
Target Player **offline** - Transfer by Phone: Should PASS
Target Player **offline** - Transfer by Phone w/ Not enough Money: Should FAIL
Target Player **offline** - Target phone number does not exist: Should FAIL

Target Player **online** - Transfer by ID: Should PASS
Target Player **online** - Transfer by Phone: Should PASS
Target Player **online** - Transfer by ID w/ Not enough Money : Should FAIL
Target Player **online** - Transfer by Phone w/ Not enough Money : Should FAIL

Transfer to non existed ID: should FAIL
Transfer to sending player's Phone number: should FAIL (cannot send money to yourself)
Transfer to sending player's ID: should FAIL (cannot send money to yourself)

**Comment by erik-sn** [comment]
Hi @BTNGaming (sorry for duplicate message, was signed into wrong account) I updated this PR to work with ESX 1.1. Sorry for the delay I had a bit of trouble getting my 1.1 to work locally, all good now.

I'd appreciate any testing you can do on this. Here is the test plan I went through on both ESX 1.1 and 1.2:

Target Player offline - Transfer by ID: Should FAIL
Target Player offline - Transfer by Phone: Should PASS
Target Player offline - Transfer by Phone w/ Not enough Money: Should FAIL
Target Player offline - Target phone number does not exist: Should FAIL

Target Player online - Transfer by ID: Should PASS
Target Player online - Transfer by Phone: Should PASS
Target Player online - Transfer by ID w/ Not enough Money : Should FAIL
Target Player online - Transfer by Phone w/ Not enough Money : Should FAIL

Transfer to non existed ID: should FAIL
Transfer to sending player's Phone number: should FAIL (cannot send money to yourself)
Transfer to sending player's ID: should FAIL (cannot send money to yourself)

**Comment by FBFezz** [comment]
This still working? Looks like a great idea

**Comment by RockySouthpaw** [comment]
The PR is still in working order. BTN just had his children born so he’s been a bit busy. 

I’ll look at the PR later with chip and Erik to see if we can just push it. Hopefully it’ll be part of our next release with the bug fixes.

**Comment by FBFezz** [comment]
Oh nice, I might have to switch to this phone, I did a pr and the phone looks sick

**Comment by RockySouthpaw** [comment]
Will try to include this in latest release. If possible.

**Comment by RockySouthpaw** [comment]
Works on 1.1 but need to test on 1.2 still.

**Comment by RockySouthpaw** [comment]
Ap

**Pull request closed without merging**
