### PR TITLE
Fixes adding a contact from recent calls

### PR DESCRIPTION
**Pull request by Archangelza1**
This adds a modal prompt to ask for the name of the user when adding from recent, it also takes a lot of line ending spaces out

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
This PR could better be better accomplished using a Router push to `/contact/0/:number`, allowing for users to add contacts using the existing system.

**Comment by Archangelza1** [comment]
Im still learning vue.js so im not 100% comfortable with Routing yet @TasoOneAsia 

but im willing to give it a try :)

**Comment by RockySouthpaw** [comment]
So the commit fixed the issue and works on mouse and keyboard. I would merge it, but Taso had a point in regards a way to better do it. Since you're willing to attempt it I'm going to leave this PR open rather than merge it. 👍🏻

**Comment by Archangelza1** [comment]
@RockySouthpaw Merge this and i will create another one with the Routing rather at a later stage :)

**Comment by RockySouthpaw** [comment]
Thank you for the PR but the team (taso) did the router method and PR'ed it.

**Pull request closed without merging**
